import { Link } from 'wouter';
import { useSearchKryv } from '@workspace/api-client-react';
import { Clapperboard, Loader2, Play, Radio, Search, Video } from 'lucide-react';

function ResultSection({ title, icon: Icon, children, count }: { title: string; icon: typeof Radio; children: React.ReactNode; count: number }) {
  if (!count) return null;
  return <section className="mt-8"><div className="flex items-center gap-2 mb-3"><Icon className="w-4 h-4 text-primary" /><h2 className="font-black text-white">{title}</h2><span className="text-xs text-white/35">{count}</span></div>{children}</section>;
}

export default function SearchPage() {
  const query = new URLSearchParams(window.location.search).get('q')?.trim() ?? '';
  const { data, isLoading } = useSearchKryv({ q: query }, { query: { enabled: query.length >= 2 } });
  const total = (data?.channels.length ?? 0) + (data?.videos.length ?? 0) + (data?.clips.length ?? 0);

  return <main className="min-h-screen bg-[#080808] text-white"><div className="max-w-6xl mx-auto px-4 sm:px-6 py-8 sm:py-12"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center"><Search className="w-5 h-5 text-primary" /></div><div><p className="text-xs font-black uppercase tracking-[0.18em] text-primary">Kryv Search</p><h1 className="mt-1 text-xl sm:text-3xl font-black">{query.length >= 2 ? <>Results for “{query}”</> : 'Search Kryv'}</h1></div></div>

    {query.length < 2 ? <div className="mt-10 rounded-2xl border border-dashed border-white/[0.12] bg-white/[0.02] p-10 text-center text-sm text-white/45">Enter at least two characters in the search field to find channels, videos, and clips.</div> : isLoading ? <div className="min-h-64 flex items-center justify-center"><Loader2 className="w-7 h-7 text-primary animate-spin" /></div> : !total ? <div className="mt-10 rounded-2xl border border-dashed border-white/[0.12] bg-white/[0.02] p-10 text-center"><Search className="w-8 h-8 mx-auto text-white/25" /><p className="mt-3 font-bold">No results found</p><p className="mt-1 text-sm text-white/40">Try a channel name, a stream topic, or a video title.</p></div> : <>
      <ResultSection title="Live channels" icon={Radio} count={data?.channels.length ?? 0}><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">{data?.channels.map(channel => <Link key={channel.id} href={`/live/${channel.slug}`} className="flex items-center gap-3 rounded-xl border border-white/[0.08] bg-white/[0.025] p-3 hover:border-primary/40 transition-colors"><div className="relative w-11 h-11 rounded-full overflow-hidden bg-primary/15 shrink-0">{channel.avatarUrl ? <img src={channel.avatarUrl} alt="" className="w-full h-full object-cover" /> : <span className="w-full h-full flex items-center justify-center font-black text-primary">{channel.displayName[0]}</span>}{channel.isLive && <span className="absolute bottom-0 right-0 w-3 h-3 rounded-full bg-red-500 border-2 border-[#101010]" />}</div><div className="min-w-0"><p className="font-black text-sm truncate">{channel.displayName}</p><p className="mt-0.5 text-xs text-white/40 truncate">{channel.isLive ? `${channel.viewerCount.toLocaleString()} watching live` : channel.streamTitle || 'Creator channel'}</p></div></Link>)}</div></ResultSection>
      <ResultSection title="Videos" icon={Video} count={data?.videos.length ?? 0}><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">{data?.videos.map(video => <Link key={video.id} href={`/watch/${video.id}`} className="group overflow-hidden rounded-xl border border-white/[0.08] bg-white/[0.025] hover:border-primary/40 transition-colors"><div className="aspect-video bg-white/[0.04] relative">{video.thumbnailUrl ? <img src={video.thumbnailUrl} alt="" className="w-full h-full object-cover" /> : <Video className="absolute inset-0 m-auto w-8 h-8 text-white/25" />}<Play className="absolute left-3 bottom-3 w-7 h-7 p-1.5 rounded-full bg-primary text-primary-foreground" /></div><div className="p-3"><p className="font-black text-sm truncate">{video.title}</p><p className="mt-1 text-xs text-white/40 truncate">{video.channelName} · {video.viewCount.toLocaleString()} views</p></div></Link>)}</div></ResultSection>
      <ResultSection title="Clips" icon={Clapperboard} count={data?.clips.length ?? 0}><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">{data?.clips.map(clip => <Link key={clip.id} href={`/clips/${clip.id}`} className="group overflow-hidden rounded-xl border border-white/[0.08] bg-white/[0.025] hover:border-primary/40 transition-colors"><div className="aspect-video bg-white/[0.04] relative">{clip.thumbnailUrl ? <img src={clip.thumbnailUrl} alt="" className="w-full h-full object-cover" /> : <Clapperboard className="absolute inset-0 m-auto w-8 h-8 text-white/25" />}<Clapperboard className="absolute left-3 bottom-3 w-7 h-7 p-1.5 rounded-full bg-primary text-primary-foreground" /></div><div className="p-3"><p className="font-black text-sm truncate">{clip.title}</p><p className="mt-1 text-xs text-white/40 truncate">{clip.channelName} · {clip.viewCount.toLocaleString()} views</p></div></Link>)}</div></ResultSection>
    </>}</div></main>;
}
