import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, useLocation } from 'wouter';
import { useSearchKryv } from '@workspace/api-client-react';
import { ArrowUpRight, Clapperboard, Loader2, Play, Radio, Search, Users, Video, X } from 'lucide-react';

type SearchSection = 'all' | 'creators' | 'watch' | 'cinema' | 'clips';

function ResultSection({ title, icon: Icon, children, count }: { title: string; icon: typeof Radio; children: React.ReactNode; count: number }) {
  if (!count) return null;
  return <section className="mt-8"><div className="mb-3 flex items-center gap-2"><Icon className="h-4 w-4 text-primary" /><h2 className="font-black text-white">{title}</h2><span className="rounded-full bg-white/[0.07] px-2 py-0.5 text-[10px] font-black text-white/40">{count}</span></div>{children}</section>;
}

export default function SearchPage() {
  const [, setLocation] = useLocation();
  const query = new URLSearchParams(window.location.search).get('q')?.trim() ?? '';
  const [draft, setDraft] = useState(query);
  const [section, setSection] = useState<SearchSection>('all');
  useEffect(() => setDraft(query), [query]);

  const { data, isLoading, isError, refetch } = useSearchKryv({ q: query }, { query: { enabled: query.length >= 2 } });
  const resultCounts = useMemo(() => ({
    creators: data?.channels.length ?? 0,
    watch: data?.videos.length ?? 0,
    cinema: data?.cinema.length ?? 0,
    clips: data?.clips.length ?? 0,
  }), [data]);
  const total = resultCounts.creators + resultCounts.watch + resultCounts.cinema + resultCounts.clips;
  const visible = (kind: Exclude<SearchSection, 'all'>) => section === 'all' || section === kind;

  const submit = (event: FormEvent) => {
    event.preventDefault();
    const next = draft.trim();
    if (next.length >= 2) setLocation(`/search?q=${encodeURIComponent(next)}`);
  };

  return <main className="min-h-screen bg-[#080808] text-white"><div className="mx-auto w-full max-w-6xl px-4 py-6 pb-[calc(2rem+env(safe-area-inset-bottom))] sm:px-6 sm:py-10"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div className="flex items-center gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border border-primary/20 bg-primary/10"><Search className="h-5 w-5 text-primary" /></div><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-primary">Kryv discovery</p><h1 className="mt-1 text-2xl font-black tracking-tight sm:text-3xl">{query.length >= 2 ? <>Results for “{query}”</> : 'Search Kryv'}</h1></div></div><p className="text-xs leading-relaxed text-white/40 sm:max-w-xs sm:text-right">Searches return public creator channels, ready Watch releases, published clips, and only rights-cleared Cinema catalog titles.</p></div>

    <form onSubmit={submit} className="relative mt-6"><Search className="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-white/35" /><input value={draft} onChange={(event) => setDraft(event.target.value)} minLength={2} maxLength={64} placeholder="Search creators, Watch, Cinema, or clips" className="h-12 w-full rounded-2xl border border-white/[0.1] bg-white/[0.035] py-3 pl-11 pr-24 text-sm font-medium text-white outline-none transition focus:border-primary/60 focus:ring-1 focus:ring-primary/20 sm:pr-32" />{draft && <button type="button" aria-label="Clear search" onClick={() => setDraft('')} className="absolute right-[4.7rem] top-1/2 -translate-y-1/2 p-2 text-white/35 hover:text-white sm:right-28"><X className="h-4 w-4" /></button>}<button type="submit" disabled={draft.trim().length < 2} className="absolute right-1.5 top-1.5 inline-flex h-9 items-center rounded-xl bg-primary px-3 text-xs font-black text-primary-foreground transition hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-45 sm:px-4">Search</button></form>

    {query.length < 2 ? <div className="mt-8 rounded-2xl border border-dashed border-white/[0.12] bg-white/[0.02] p-8 text-center sm:p-12"><Search className="mx-auto h-8 w-8 text-white/20" /><h2 className="mt-4 text-lg font-black text-white">Find your next Kryv destination</h2><p className="mx-auto mt-2 max-w-md text-sm leading-relaxed text-white/40">Enter at least two characters to search public creators, ready Watch releases, published clips, and owner-cleared Cinema titles.</p><div className="mx-auto mt-6 grid max-w-lg grid-cols-2 gap-2 text-left sm:grid-cols-4"><span className="rounded-xl border border-white/[0.08] bg-black/20 p-3 text-xs font-bold text-white/55"><Users className="mb-2 h-4 w-4 text-primary" />Creators</span><span className="rounded-xl border border-white/[0.08] bg-black/20 p-3 text-xs font-bold text-white/55"><Video className="mb-2 h-4 w-4 text-primary" />Watch</span><span className="rounded-xl border border-white/[0.08] bg-black/20 p-3 text-xs font-bold text-white/55"><Clapperboard className="mb-2 h-4 w-4 text-primary" />Cinema</span><span className="rounded-xl border border-white/[0.08] bg-black/20 p-3 text-xs font-bold text-white/55"><Play className="mb-2 h-4 w-4 text-primary" />Clips</span></div></div> : isLoading ? <div className="flex min-h-64 items-center justify-center" role="status"><Loader2 className="h-7 w-7 animate-spin text-primary" /><span className="sr-only">Searching Kryv</span></div> : isError ? <div className="mt-8 rounded-2xl border border-red-300/20 bg-red-400/[0.05] p-6 text-center" role="alert"><p className="font-black text-red-100">Search is temporarily unavailable</p><p className="mt-2 text-sm leading-relaxed text-red-100/70">Try again in a moment. No partial or fabricated results are shown while the search service is unavailable.</p><button type="button" onClick={() => refetch()} className="mt-4 inline-flex min-h-10 items-center rounded-xl border border-red-200/25 bg-red-200/[0.08] px-4 text-xs font-black text-red-50 transition hover:bg-red-200/[0.14]">Retry search</button></div> : !total ? <div className="mt-8 rounded-2xl border border-dashed border-white/[0.12] bg-white/[0.02] p-8 text-center sm:p-12"><Search className="mx-auto h-8 w-8 text-white/25" /><h2 className="mt-3 font-black text-white">No public results found</h2><p className="mt-1 text-sm text-white/40">Try a creator name, title, topic, or a shorter phrase.</p></div> : <>
      <div className="mt-6 -mx-4 flex gap-2 overflow-x-auto px-4 pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden sm:mx-0 sm:px-0">{([['all', 'All', total], ['creators', 'Creators', resultCounts.creators], ['watch', 'Watch', resultCounts.watch], ['cinema', 'Cinema', resultCounts.cinema], ['clips', 'Clips', resultCounts.clips]] as Array<[SearchSection, string, number]>).map(([id, label, count]) => <button key={id} type="button" onClick={() => setSection(id)} aria-pressed={section === id} className={`inline-flex h-11 shrink-0 items-center gap-2 rounded-xl border px-4 text-xs font-black transition ${section === id ? 'border-primary/50 bg-primary text-primary-foreground' : 'border-white/[0.1] bg-white/[0.025] text-white/55 hover:text-white'}`}>{label}<span className={`rounded-full px-1.5 py-0.5 text-[10px] ${section === id ? 'bg-black/15' : 'bg-white/[0.08]'}`}>{count}</span></button>)}</div>
      {visible('creators') && <ResultSection title="Creators" icon={Radio} count={resultCounts.creators}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data?.channels.map(channel => <Link key={channel.id} href={`/profile/${channel.slug}`} className="group flex min-h-[5.5rem] items-center gap-3 rounded-2xl border border-white/[0.08] bg-white/[0.025] p-3 transition hover:border-primary/45 hover:bg-primary/[0.04]"><div className="relative h-12 w-12 shrink-0 overflow-hidden rounded-2xl bg-primary/15">{channel.avatarUrl ? <img src={channel.avatarUrl} alt="" loading="lazy" decoding="async" className="h-full w-full object-cover" /> : <span className="flex h-full w-full items-center justify-center font-black text-primary">{channel.displayName[0]}</span>}{channel.isLive && <span className="absolute bottom-1 right-1 h-3 w-3 rounded-full border-2 border-[#101010] bg-red-500" />}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-black text-white transition group-hover:text-primary">{channel.displayName}</p><p className="mt-1 truncate text-xs text-white/40">{channel.isLive ? `${channel.viewerCount.toLocaleString()} watching live` : channel.streamTitle || 'Public creator profile'}</p></div><ArrowUpRight className="h-4 w-4 shrink-0 text-white/25 transition group-hover:text-primary" /></Link>)}</div></ResultSection>}
      {visible('watch') && <ResultSection title="Watch releases" icon={Video} count={resultCounts.watch}><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{data?.videos.map(video => <Link key={video.id} href={`/watch/${video.id}`} className="group overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.025] transition hover:-translate-y-0.5 hover:border-primary/45"><div className="relative aspect-video bg-white/[0.04]">{video.thumbnailUrl ? <img src={video.thumbnailUrl} alt="" loading="lazy" decoding="async" className="h-full w-full object-cover" /> : <Video className="absolute inset-0 m-auto h-7 w-7 text-white/25" />}<Play className="absolute bottom-2 left-2 h-7 w-7 rounded-full bg-primary p-1.5 text-primary-foreground" /></div><div className="p-3"><p className="truncate text-sm font-black text-white">{video.title}</p><p className="mt-1 truncate text-[11px] text-white/40">{video.channelName} · {video.viewCount.toLocaleString()} views</p></div></Link>)}</div></ResultSection>}
      {visible('cinema') && <ResultSection title="Cinema catalog" icon={Clapperboard} count={resultCounts.cinema}><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{data?.cinema.map(title => <Link key={title.id} href={`/cinema/${title.id}`} className="group overflow-hidden rounded-2xl border border-white/[0.08] bg-[#0b0e14] transition hover:-translate-y-0.5 hover:border-primary/45"><div className="relative aspect-[2/3] bg-black/45">{title.posterUrl ? <img src={title.posterUrl} alt="" loading="lazy" decoding="async" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /> : <Clapperboard className="absolute inset-0 m-auto h-8 w-8 text-white/20" />}<div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/85 to-transparent p-3"><span className="rounded-full border border-primary/30 bg-primary/15 px-2 py-1 text-[9px] font-black uppercase tracking-wider text-primary">Cinema</span></div></div><div className="p-3"><p className="truncate text-sm font-black text-white">{title.title}</p><p className="mt-1 line-clamp-2 text-[11px] leading-relaxed text-white/40">{title.synopsis || 'Owner-curated Cinema production.'}</p></div></Link>)}</div></ResultSection>}
      {visible('clips') && <ResultSection title="Clips" icon={Clapperboard} count={resultCounts.clips}><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{data?.clips.map(clip => <Link key={clip.id} href={`/clips/${clip.id}`} className="group overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.025] transition hover:-translate-y-0.5 hover:border-primary/45"><div className="relative aspect-video bg-white/[0.04]">{clip.thumbnailUrl ? <img src={clip.thumbnailUrl} alt="" loading="lazy" decoding="async" className="h-full w-full object-cover" /> : <Clapperboard className="absolute inset-0 m-auto h-7 w-7 text-white/25" />}<Clapperboard className="absolute bottom-2 left-2 h-7 w-7 rounded-full bg-primary p-1.5 text-primary-foreground" /></div><div className="p-3"><p className="truncate text-sm font-black text-white">{clip.title}</p><p className="mt-1 truncate text-[11px] text-white/40">{clip.channelName} · {clip.viewCount.toLocaleString()} views</p></div></Link>)}</div></ResultSection>}
    </>}</div></main>;
}
