import { useListCategories, useListVideos } from '@workspace/api-client-react';
import { ArrowUpRight, Clock3, Film, Flame, Loader2, Play, Search, SlidersHorizontal, Sparkles } from 'lucide-react';
import { type FormEvent, useMemo, useState } from 'react';
import { Link } from 'wouter';
import { VideoCard } from '@/components/VideoCard';

function RailHeading({ eyebrow, title, detail, icon: Icon }: { eyebrow: string; title: string; detail?: string; icon: typeof Sparkles }) {
  return <div className="mb-4 sm:mb-5"><div className="flex items-center gap-2 text-primary"><Icon className="h-4 w-4" /><span className="text-[11px] font-black uppercase tracking-[0.18em]">{eyebrow}</span></div><h2 className="mt-1 text-2xl font-black tracking-tight text-white sm:text-3xl">{title}</h2>{detail && <p className="mt-1 text-sm text-white/45">{detail}</p>}</div>;
}

export default function WatchHome() {
  const [search, setSearch] = useState('');
  const [inputValue, setInputValue] = useState('');
  const [activeCategoryId, setActiveCategoryId] = useState<number | undefined>();

  const { data: categories = [] } = useListCategories({ kind: 'genre' });
  const activeCategory = useMemo(() => categories.find(category => category.id === activeCategoryId), [activeCategoryId, categories]);
  const { data: videos = [], isLoading, isError, refetch: refetchVideos } = useListVideos({ contentType: 'upload', search: search || undefined, categorySlug: activeCategory?.slug });

  const submitSearch = (event: FormEvent) => { event.preventDefault(); setSearch(inputValue.trim()); };
  const clearFilters = () => { setSearch(''); setInputValue(''); setActiveCategoryId(undefined); };
  const isFiltered = Boolean(search || activeCategoryId !== undefined);
  const featuredVideo = videos[0];
  const categoryRails = useMemo(() => categories.map(category => ({ category, videos: videos.filter(video => video.categoryId === category.id) })).filter(group => group.videos.length > 0), [categories, videos]);

  return (
    <div className="relative z-10 mx-auto w-full max-w-[1600px] px-4 py-5 sm:px-6 sm:py-8 lg:px-8 lg:py-10">
      <section className="relative overflow-hidden rounded-2xl border border-white/[0.08] bg-gradient-to-br from-primary/[0.12] via-[#11151a] to-cyan-500/[0.08] px-5 py-7 sm:rounded-3xl sm:px-8 sm:py-10 lg:px-10">
        <div className="pointer-events-none absolute -right-20 -top-24 h-64 w-64 rounded-full bg-primary/20 blur-3xl" /><div className="pointer-events-none absolute -bottom-32 left-1/3 h-56 w-56 rounded-full bg-cyan-400/10 blur-3xl" />
        <div className="relative grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(320px,0.75fr)] lg:items-end lg:gap-10">
          <div className="max-w-2xl"><div className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-[10px] font-black uppercase tracking-[0.18em] text-primary"><Film className="h-3.5 w-3.5" /> Kryv Watch</div><h1 className="mt-4 text-3xl font-black tracking-tight text-white sm:text-4xl lg:text-5xl">Every creator story, ready when you are.</h1><p className="mt-3 max-w-xl text-sm leading-relaxed text-white/60 sm:text-base">Kryv Watch is the on-demand home for creator uploads that have completed processing and are ready to play.</p></div>
          <form onSubmit={submitSearch} className="w-full rounded-2xl border border-white/[0.1] bg-black/30 p-2 backdrop-blur-sm"><label htmlFor="watch-search" className="sr-only">Search Kryv Watch</label><div className="flex items-center gap-2"><Search className="ml-2 h-4 w-4 shrink-0 text-white/40" /><input id="watch-search" type="search" value={inputValue} onChange={event => setInputValue(event.target.value)} placeholder="Search the Watch library" maxLength={64} className="h-11 min-w-0 flex-1 bg-transparent px-1 text-sm text-white outline-none placeholder:text-white/35" /><button type="submit" className="inline-flex h-10 shrink-0 items-center gap-1.5 rounded-xl bg-primary px-3 text-xs font-black text-primary-foreground transition-colors hover:bg-primary/90 sm:px-4"><Search className="h-3.5 w-3.5" /> <span className="hidden sm:inline">Search</span></button></div></form>
        </div>
      </section>

      <div className="mt-6 -mx-4 flex gap-2 overflow-x-auto px-4 pb-2 sm:mx-0 sm:mt-8 sm:px-0 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden" aria-label="Watch categories">
        <button onClick={() => setActiveCategoryId(undefined)} className={`inline-flex min-h-10 shrink-0 items-center rounded-full px-4 text-sm font-bold transition-all ${activeCategoryId === undefined ? 'bg-primary text-primary-foreground shadow-[0_0_18px_hsl(var(--primary)/0.3)]' : 'border border-white/[0.09] bg-white/[0.045] text-white/65 hover:border-white/20 hover:bg-white/[0.08] hover:text-white'}`}>All uploads</button>
        {categories.map(category => <button key={category.id} onClick={() => { setActiveCategoryId(category.id); setSearch(''); setInputValue(''); }} className={`inline-flex min-h-10 shrink-0 items-center rounded-full px-4 text-sm font-bold transition-all ${activeCategoryId === category.id ? 'bg-primary text-primary-foreground shadow-[0_0_18px_hsl(var(--primary)/0.3)]' : 'border border-white/[0.09] bg-white/[0.045] text-white/65 hover:border-white/20 hover:bg-white/[0.08] hover:text-white'}`}>{category.name}</button>)}
      </div>

      {isLoading ? <div className="flex min-h-[42vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div> : isError ? <section className="mt-6 rounded-2xl border border-red-300/20 bg-red-400/[0.05] p-6 text-center sm:mt-8 sm:p-10"><h2 className="text-xl font-black text-red-100">Watch is temporarily unavailable</h2><p className="mx-auto mt-2 max-w-md text-sm leading-relaxed text-red-100/70">Kryv cannot safely show a partial or fabricated Watch library while the ready-upload inventory is unavailable.</p><button type="button" onClick={() => refetchVideos()} className="mt-5 inline-flex min-h-10 items-center rounded-xl border border-red-200/25 bg-red-200/[0.08] px-4 text-sm font-black text-red-50 transition hover:bg-red-200/[0.14]">Retry Watch</button></section> : videos.length === 0 ? (
        <section className="mt-6 overflow-hidden rounded-2xl border border-white/[0.08] bg-gradient-to-br from-white/[0.035] to-primary/[0.055] p-6 sm:mt-8 sm:p-10"><div className="max-w-md"><div className="flex h-12 w-12 items-center justify-center rounded-2xl border border-primary/25 bg-primary/10"><Play className="h-5 w-5 fill-primary text-primary" /></div><h2 className="mt-5 text-xl font-black text-white">{isFiltered ? 'Nothing matched that selection.' : 'The Watch library is preparing for its first premiere.'}</h2><p className="mt-2 text-sm leading-relaxed text-white/50">{isFiltered ? 'Try a broader title or return to the complete library.' : 'Creator uploads will appear here as soon as they are processed and published.'}</p>{isFiltered ? <button onClick={clearFilters} className="mt-5 inline-flex min-h-10 items-center gap-2 rounded-xl border border-primary/35 bg-primary/10 px-4 text-sm font-black text-primary transition-colors hover:bg-primary hover:text-primary-foreground"><SlidersHorizontal className="h-4 w-4" /> Clear filters</button> : <Link href="/dashboard/watch" className="mt-5 inline-flex min-h-10 items-center gap-2 rounded-xl border border-primary/35 bg-primary/10 px-4 text-sm font-black text-primary transition-colors hover:bg-primary hover:text-primary-foreground"><Play className="h-4 w-4" /> Publish your first upload</Link>}</div></section>
      ) : isFiltered ? (
        <section className="mt-8"><div className="mb-4 flex flex-col gap-3 sm:mb-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-primary"><Search className="h-4 w-4" /><span className="text-[11px] font-black uppercase tracking-[0.18em]">Search results</span></div><h2 className="mt-1 text-2xl font-black text-white sm:text-3xl">{search ? `Results for “${search}”` : activeCategory?.name}</h2></div><button onClick={clearFilters} className="text-left text-xs font-black text-primary hover:text-white">Clear filters</button></div><div className="grid grid-cols-1 gap-x-4 gap-y-7 sm:grid-cols-2 sm:gap-x-5 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5">{videos.map(video => <VideoCard key={video.id} video={video} />)}</div></section>
      ) : (
        <div className="mt-8 space-y-12 sm:mt-10 sm:space-y-14">
          {featuredVideo && <section className="relative overflow-hidden rounded-3xl border border-white/[0.08] bg-[#0b0e14]"><div className="absolute inset-0">{featuredVideo.thumbnailUrl && <img src={featuredVideo.thumbnailUrl} alt="" className="h-full w-full object-cover opacity-45" />}<div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(11,14,20,0.96)_0%,rgba(11,14,20,0.76)_45%,rgba(11,14,20,0.25)_100%)]" /></div><div className="relative flex min-h-[350px] max-w-2xl flex-col justify-end p-6 sm:min-h-[410px] sm:p-9"><div className="inline-flex w-fit items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-[10px] font-black uppercase tracking-[0.18em] text-primary"><Flame className="h-3.5 w-3.5" /> Featured upload</div><h2 className="mt-4 text-2xl font-black tracking-tight text-white sm:text-4xl">{featuredVideo.title}</h2><p className="mt-2 text-sm text-white/60">From {featuredVideo.channelName}{featuredVideo.categoryName ? ` · ${featuredVideo.categoryName}` : ''}</p><div className="mt-6 flex flex-wrap items-center gap-3"><Link href={`/watch/${featuredVideo.id}`}><span className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-white px-4 text-sm font-black text-black transition-transform hover:-translate-y-0.5"><Play className="h-4 w-4 fill-current" /> Play</span></Link><span className="inline-flex items-center gap-1.5 text-xs font-bold text-white/55"><Clock3 className="h-3.5 w-3.5" /> {featuredVideo.viewCount.toLocaleString()} views</span></div></div></section>}

          <section><RailHeading eyebrow="Fresh uploads" title="Latest on Kryv Watch" detail="New creator video, ready to watch." icon={Clock3} /><div className="-mx-4 flex snap-x snap-mandatory gap-4 overflow-x-auto px-4 pb-3 sm:mx-0 sm:px-0 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{videos.slice(featuredVideo ? 1 : 0).map(video => <div key={video.id} className="w-[78vw] shrink-0 snap-start sm:w-72"><VideoCard video={video} /></div>)}</div></section>

          {categoryRails.map(({ category, videos: categoryVideos }) => <section key={category.id}><div className="mb-4 flex items-end justify-between gap-4"><RailHeading eyebrow="Category" title={category.name} detail={`${categoryVideos.length} available ${categoryVideos.length === 1 ? 'upload' : 'uploads'}`} icon={Sparkles} /><button onClick={() => setActiveCategoryId(category.id)} className="mb-1 inline-flex shrink-0 items-center gap-1 text-xs font-black text-primary hover:text-white">Explore <ArrowUpRight className="h-3.5 w-3.5" /></button></div><div className="-mx-4 flex snap-x snap-mandatory gap-4 overflow-x-auto px-4 pb-3 sm:mx-0 sm:px-0 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{categoryVideos.map(video => <div key={video.id} className="w-[78vw] shrink-0 snap-start sm:w-72"><VideoCard video={video} /></div>)}</div></section>)}
        </div>
      )}
    </div>
  );
}
