import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import meRouter from "./me";
import categoriesRouter from "./categories";
import discoverRouter from "./discover";
import channelsRouter from "./channels";
import chatRouter from "./chat";
import videosRouter from "./videos";
import clipsRouter from "./clips";
import engagementRouter from "./engagement";
import cinemaRouter from "./cinema";
import adminRouter from "./admin";
import locationRouter from "./location";
import streamingRouter from "./streaming";
import adsRouter from "./ads";
import ownerCinemaRouter from "./owner-cinema";
import creatorFinanceRouter from "./creator-finance";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(meRouter);
router.use(categoriesRouter);
router.use(discoverRouter);
router.use(channelsRouter);
router.use(chatRouter);
router.use(videosRouter);
router.use(clipsRouter);
router.use(engagementRouter);
router.use(cinemaRouter);
router.use(adminRouter);
router.use(locationRouter);
router.use(streamingRouter);
router.use(adsRouter);
router.use(ownerCinemaRouter);
router.use(creatorFinanceRouter);

export default router;
