import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Check, Clipboard, Copy, Eye, EyeOff, KeyRound, Monitor, RefreshCw, Radio, Save, Server, ShieldAlert, SlidersHorizontal, WifiOff } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { formatDate, PageError, PageHeader, PageLoading } from "./creatorShared";

function CopyField({ label, value, secret, allowCopy, onToggle, visible }: { label: string; value?: string | null; secret?: boolean; allowCopy?: boolean; onToggle?: () => void; visible?: boolean }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    if (!value || !allowCopy) { toast.error(secret ? "Generate a new key to copy it in this session." : "No stream server is configured yet."); return; }
    try { await navigator.clipboard.writeText(value); setCopied(true); toast.success(`${label} copied to clipboard.`); window.setTimeout(() => setCopied(false), 1800); } catch { toast.error("Clipboard access was unavailable. Copy the value manually."); }
  };
  const shown = secret && !visible ? (value ? "••••••••••••••••••••••••••" : "No key generated") : (value || "Not configured");
  return <div><div className="mb-2 flex items-center justify-between"><label className="kryv-label">{label}</label>{secret && <span className="text-[11px] text-white/36">Visible only after generation</span>}</div><div className="flex items-center gap-2"><div className="min-w-0 flex-1 truncate rounded-xl border border-white/10 bg-black/25 px-3.5 py-3 font-mono text-sm text-white/74">{shown}</div>{secret && <Button variant="outline" size="icon" onClick={onToggle} className="kryv-action h-11 w-11 shrink-0 rounded-xl border-white/10 bg-white/[0.03] text-white/65 hover:bg-white/[0.08] hover:text-white" aria-label={visible ? "Hide stream key" : "Reveal stream key"}>{visible ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</Button>}<Button variant="outline" size="icon" onClick={copy} className="kryv-action h-11 w-11 shrink-0 rounded-xl border-white/10 bg-white/[0.03] text-white/65 hover:bg-white/[0.08] hover:text-white" aria-label={`Copy ${label}`}>{copied ? <Check className="h-4 w-4 text-emerald-300" /> : <Copy className="h-4 w-4" />}</Button></div></div>;
}

export default function StreamSetupPage() {
  const utils = trpc.useUtils();
  const { data, isLoading, isError, error, refetch } = trpc.creator.dashboard.useQuery();
  const [streamTitle, setStreamTitle] = useState("");
  const [category, setCategory] = useState("");
  const [revealedKey, setRevealedKey] = useState<string | null>(null);
  const [showKey, setShowKey] = useState(false);
  const updateStream = trpc.creator.stream.update.useMutation({ onSuccess: async () => { await utils.creator.dashboard.invalidate(); toast.success("Stream information saved."); }, onError: (issue) => toast.error(issue.message) });
  const rotateKey = trpc.creator.stream.rotateKey.useMutation({ onSuccess: async (result) => { setRevealedKey(result.streamKey); setShowKey(true); await utils.creator.dashboard.invalidate(); toast.success("New stream key generated. Copy it before leaving this page."); }, onError: (issue) => toast.error(issue.message) });

  useEffect(() => { if (data) { setStreamTitle(data.stream.streamTitle); setCategory(data.stream.category || ""); } }, [data?.stream.streamTitle, data?.stream.category]);
  if (isLoading) return <PageLoading />;
  if (isError || !data) return <PageError message={error?.message} onRetry={() => refetch()} />;
  const hasServer = Boolean(data.stream.rtmpServerUrl);
  const hasKey = Boolean(revealedKey || data.stream.hasStreamKey);
  const keyValue = revealedKey || data.stream.streamKeyPreview || "";

  return <div className="mx-auto max-w-7xl"><PageHeader eyebrow="Creator studio / stream" title="Stream setup" description="Set your broadcast details, generate a protected stream key, and connect your encoder to Kryv." action={<span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.035] px-3 py-2 text-xs font-bold text-white/55">{data.stream.isLive ? <span className="h-2 w-2 rounded-full bg-rose-300" /> : <span className="h-2 w-2 rounded-full bg-white/30" />}{data.stream.isLive ? "Broadcasting now" : "Offline"}</span>} />
    {!hasServer && <div className="mb-5 flex gap-3 rounded-2xl border border-amber-300/20 bg-amber-300/[0.07] p-4"><WifiOff className="mt-0.5 h-5 w-5 shrink-0 text-amber-200" /><div><p className="text-sm font-bold text-amber-100">A live ingest endpoint is not connected yet</p><p className="mt-1 text-sm leading-6 text-amber-100/65">Set a secure <code className="rounded bg-black/20 px-1.5 py-0.5">KRYV_RTMP_SERVER_URL</code> environment value before creators can send a real broadcast. Your stream key remains protected in the dashboard.</p></div></div>}
    <div className="grid grid-cols-1 gap-5 xl:grid-cols-[1.15fr_.85fr]">
      <div className="space-y-5"><section className="kryv-card rounded-3xl p-5 sm:p-6"><div className="mb-5 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-300/10 text-violet-200"><Radio className="h-5 w-5" /></span><div><p className="kryv-label">Step 1</p><h2 className="kryv-title text-xl font-bold text-white">Broadcast details</h2></div></div><div className="grid gap-4 sm:grid-cols-2"><label className="block sm:col-span-2"><span className="kryv-label mb-2 block">Stream title</span><input value={streamTitle} onChange={(event) => setStreamTitle(event.target.value)} maxLength={140} placeholder="What are you streaming today?" className="kryv-focus h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3.5 text-sm text-white placeholder:text-white/28" /></label><label className="block"><span className="kryv-label mb-2 block">Category</span><input value={category} onChange={(event) => setCategory(event.target.value)} maxLength={80} placeholder="Gaming, IRL, Music…" className="kryv-focus h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3.5 text-sm text-white placeholder:text-white/28" /></label><div className="flex items-end"><Button onClick={() => updateStream.mutate({ streamTitle, category: category || undefined })} disabled={updateStream.isPending} className="kryv-action h-11 w-full rounded-xl bg-violet-300 font-extrabold text-[#15111d] hover:bg-violet-200"><Save className="mr-2 h-4 w-4" />{updateStream.isPending ? "Saving…" : "Save details"}</Button></div></div></section>
        <section className="kryv-card rounded-3xl p-5 sm:p-6"><div className="mb-5 flex flex-wrap items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-fuchsia-300/10 text-fuchsia-200"><KeyRound className="h-5 w-5" /></span><div className="mr-auto"><p className="kryv-label">Step 2</p><h2 className="kryv-title text-xl font-bold text-white">Stream URL & key</h2></div><AlertDialog><AlertDialogTrigger asChild><Button variant="outline" className="kryv-action rounded-xl border-white/12 bg-white/[0.035] text-white hover:bg-white/[0.08] hover:text-white"><RefreshCw className="mr-2 h-4 w-4" />{hasKey ? "Regenerate key" : "Generate key"}</Button></AlertDialogTrigger><AlertDialogContent className="border-white/10 bg-[#171722] text-white"><AlertDialogHeader><AlertDialogTitle>{hasKey ? "Regenerate your stream key?" : "Generate a new stream key?"}</AlertDialogTitle><AlertDialogDescription className="leading-6 text-white/55">{hasKey ? "Your existing key will stop working immediately. Any encoder using it must be updated with the new key." : "A new encrypted stream key will be created for this creator account. You can copy it once after generation."}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel className="border-white/12 bg-transparent text-white hover:bg-white/10 hover:text-white">Cancel</AlertDialogCancel><AlertDialogAction onClick={() => rotateKey.mutate()} className="bg-violet-300 text-[#17111e] hover:bg-violet-200">{rotateKey.isPending ? "Generating…" : "Continue"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div><div className="space-y-4"><CopyField label="RTMP server URL" value={data.stream.rtmpServerUrl} allowCopy={hasServer} /><CopyField label="Stream key" value={keyValue} secret visible={showKey} onToggle={() => setShowKey((value) => !value)} allowCopy={Boolean(revealedKey)} /><div className="flex gap-3 rounded-xl border border-rose-300/20 bg-rose-300/[0.07] p-3.5"><ShieldAlert className="mt-0.5 h-4 w-4 shrink-0 text-rose-200" /><p className="text-xs leading-5 text-rose-100/76">Treat this key like a password. Kryv stores only a one-way hash and never displays a prior key again after you leave this page.</p></div>{data.stream.lastKeyRotatedAt && <p className="text-xs text-white/36">Last changed {formatDate(data.stream.lastKeyRotatedAt)}.</p>}</div></section></div>
      <aside className="space-y-5"><section className="kryv-card rounded-3xl p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-300/10 text-cyan-200"><SlidersHorizontal className="h-5 w-5" /></span><div><p className="kryv-label">Recommended encoder settings</p><h2 className="kryv-title text-xl font-bold text-white">Stable, high-quality video</h2></div></div><div className="mt-5 grid grid-cols-3 gap-2">{[["1920×1080","Resolution"],["60 FPS","Framerate"],["CBR","Rate control"],["8,000 Kbps","Bitrate"],["2 sec","Keyframe"],["H.264","Codec"]].map(([value, label]) => <div className="kryv-card-subtle rounded-xl p-3" key={label}><p className="text-sm font-extrabold text-white">{value}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[0.08em] text-white/38">{label}</p></div>)}</div><p className="mt-4 text-xs leading-5 text-white/43">Tune bitrate and resolution to your actual upstream bandwidth. Start with these values, then reduce load if your encoder reports dropped frames.</p></section><section className="kryv-card rounded-3xl p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-300/10 text-emerald-200"><Monitor className="h-5 w-5" /></span><div><p className="kryv-label">Setup guide</p><h2 className="kryv-title text-xl font-bold text-white">Connect OBS</h2></div></div><ol className="mt-5 space-y-4">{[["Open OBS settings","Choose Settings → Stream."],["Select Custom service","Choose a custom RTMP service rather than a preset."],["Paste your server and key","Copy both values from Step 2 above."],["Start streaming","Kryv will detect the feed after an ingest provider is connected."]].map(([title, copy], index) => <li className="flex gap-3" key={title}><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full border border-cyan-300/20 bg-cyan-300/10 text-[10px] font-extrabold text-cyan-200">{index + 1}</span><div><p className="text-sm font-bold text-white/82">{title}</p><p className="mt-0.5 text-xs leading-5 text-white/43">{copy}</p></div></li>)}</ol></section><section className="rounded-3xl border border-violet-300/20 bg-gradient-to-br from-violet-300/[0.12] to-fuchsia-300/[0.05] p-5"><Server className="h-5 w-5 text-violet-100" /><p className="mt-3 text-sm font-bold text-white">Ready for a real live pipeline</p><p className="mt-1 text-xs leading-5 text-violet-100/64">The dashboard securely supports per-creator credentials. Connect a streaming ingest and analytics provider to surface live status and verified viewer counts.</p></section></aside>
    </div></div>;
}
